### PR TITLE
adds/updates records; uses jq instead of grep

### PR DESCRIPTION
**Pull request by acolomba**
- adds a record if it doesn't exist yet
- uses jq to extract information more reliably from cloudflare responses

### CODE REVIEW

**Comment by joshuaavalon** [comment]
I don't have time to check it yet. I will check it out later this week.

**Comment by acolomba** [comment]
hey there, just a gentle reminder to merge this, if it looks good to you

**Comment by joshuaavalon** [comment]
@acolomba Sorry for getting back to you so late. I forgot about this. Some minor things I would like you to change before accepting this pull request.

First, getting `record_id` from Cloudflare can return more than one record, i.e. `A`, `MX`, `TXT`. We cannot ensure it is always `A` record at `result[0]`. While verify this is difficult with grep, I think this is possible with jq.

* Get the `id` from the object with `"type": "A"` instead of `result[0]`
* If it does not have a A record, check if it contains a CNAME. If yes, we should print an alert and terminate itself.
* If it does not contains  either A or CNAME, we should only create a new record if user enable it in environment variable like `CREATE_IF_NOT_EXIST`. Otherwise, it should terminate itself. Default should be false.

With jq, I think we should be able to provide more checking and meaningful warning. Also, I do not think creating a record by default is a good idea. It should let users enable it if they want.

Last, I would like you to use `"` instead `'` for consistent.

I do not familiar with the syntax of jq. It would nice if you can make an update on this.

**Comment by acolomba** [comment]
Good ideas. Can do.

**Comment by joshuaavalon** [comment]
`!/bin/bash` would not work. Alpine does not have bash. Does there any reason to use bash over sh?

**Comment by acolomba** [comment]
Yes, I'm using bash-only features such as here-variables. This is still work in progress btw.

**Comment by acolomba** [comment]
Implemented the features we discussed plus some other stuff.

**Comment by acolomba** [comment]
Oh and the quoting style is not about picking one or the other -- it's about indicating that the jq code is not meant to have substitutions. Same thing one would do with awk for instance.

**Pull request merged**
